### ISSUE TITLE
Veins panel filename mismatch

### ISSUE THREAD

**Issue by ExistentiaVirae** [JohannAsbjoernson/JA#1]
The panel for Veins is named "Panel2hpBER.svg" but the source file tries to load "res/panels/Panel2HPBER.svg". The module still works, but on Linux it makes a 16hp shadow for a panel. When I renamed the SVG file, it loaded properly.

**Comment by JohannAsbjoernson** [comment]
thanks!
I already found out earlier, that Linux is icky about up- and lower case writing. 
Corrected and updated the release.
